# Your Fabric Warehouse SQL Endpoint
server = 'l23jvmddsbrerl5c25nljc52oq-3dyzqrdrcf7uxgalftx4qvmqza.datawarehouse.fabric.microsoft.com'
database = 'ONEHFM'
username = 'mohamed.abdelmaksoud@maf.ae'
password = 'MAF@4242'
driver = "ODBC Driver 17 for SQL Server"  
